language: python
sudo: false

matrix:
    include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=py2-cover,py3-cover,coverage
    - python: 3.6
      env: TOXENV=py36
    - python: nightly
      env: TOXENV=py37
    allow_failures:
    - env: TOXENV=py37

before_install:
    - python -m pip install --upgrade setuptools pip virtualenv

# command to install dependencies
install:
    - pip install -r requirements-build.txt

# command to run tests
script:
    - tox

